apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-reader
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-reader-binding
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: backend-reader
  apiGroup: rbac.authorization.k8s.io